---

- hosts: all
  remote_user: ansible
  become: yes
  become_user: root

  tasks:
  - name: 'Apt auto-patching'
    block:
    - name: Apt update cache
      apt:
        update_cache: yes
    - name: Apt Upgrade
      apt:
        upgrade: yes
    - name: Apt dist upgrade
      apt:
        upgrade: dist
    when: ansible_facts['os_family'] == "Debian"

  - name: Yum autopatching
    block:
    - name: yum update
      yum:
        name: '*'
        state: latest
    when: ansible_facts['os_family'] == "RedHat"


