---
- name: Flash SD card
  hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Flash SD card
    # Do some verification on which device to run against?
    shell: unzip -p {{rpi_zip_file}}|dd bs=4M of=/dev/sdc conv=fsync status=progress
    args:
      chdir: '/root'
      executable: /bin/bash
  - name: Make sure mount folder exists
    file:
      path: /mnt/rpi
      state: directory
      mode: '0775'
  - name: Mount /boot on SDcard
    ansible.posix.mount:
      src: /dev/sdc1
      path: /mnt/rpi
      fstype: vfat
      state: mounted
  - name: Create SSH file so SSH is enabled
    file:
      path: /mnt/rpi/ssh
      state: touch
  - name: unmount /boot on SDcard
    ansible.posix.mount:
      src: /dev/sdc1
      path: /mnt/rpi
      state: unmounted

  - name: Mount / on SDcard
    ansible.posix.mount:
      src: /dev/sdc2
      path: /mnt/rpi
      fstype: ext4
      state: mounted
  # Add local SSH key to pi user
  - name: Unmount / on SDcard
    ansible.posix.mount:
      src: /dev/sdc2
      path: /mnt/rpi
      state: unmounted
